apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: ci-load-test
spec:
  replicas: 1
  selector:
    matchLabels: { app: bar }
  template:
    metadata:
      labels: { app: bar }
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:0.2.3
          args: ["-text=bar", "-listen=:5678"]
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet: { path: /, port: 5678 }
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet: { path: /, port: 5678 }
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: bar
  namespace: ci-load-test
spec:
  selector: { app: bar }
  ports:
    - port: 80
      targetPort: 5678
